[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dvdpy"
version = "0.1"

[tool.setuptools]
ext-modules = [
  {name = "dvdpy", sources = ["dvdpy.c"]}
]
